FROM node:18-alpine


# OpenRouter Configuration
ENV VITE_OPENROUTER_API_KEY=$VITE_OPENROUTER_API_KEY
ENV VITE_OPENROUTER_BASE_URL=VITE_OPENROUTER_BASE_URL
ENV VITE_VISION_MODEL=$VITE_VISION_MODEL
ENV VITE_ANALYSIS_MODEL=$VITE_VISION_MODEL
ENV VITE_USE_MOCK=$VITE_USE_MOCK

WORKDIR /app

COPY package.json .

RUN npm install

RUN npm i -g serve

COPY . .

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-s", "dist" ]